name: Suitcase
main: me.eighth.suitcase.Suitcase
version: 0.2
author: eighth
authors:
- HavaTequila
website: www.gamez-pla.net
description: Suitcase is a rating system for players and a warning system for admins with website integration.

commands:
  suitcase:
    description: Rate and warn players.
    aliases: [sc, suit]
    permission: suitcase
    
permissions:
  suitcase.*:
    description: Gives access to all Suitcase commands
    children:
      suitcase.help: true
      suitcase.rate: true
      suitcase.warn: true
      suitcase.admin: true
  suitcase.help:
    description: Shows command help and info
  suitcase.rate:
    description: Rates other players or view rating
  suitcase.warn:
    description: Warns or forgives players
  suitcase.admin:
    description: Gives permission to reload or reset Suitcase