name: Suitcase
main: me.eight.suitcase.suitcase
version: 0.1
authors: [eighth, HavaTequila]
description: >
             Suitcase is a rating system for players and a warning system for admins.
commands:
